name: My Workflow

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: fedora-latest
    steps:          
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup docker env
        uses: docker://centos:8
      - name: Build project
        run: |
          yum update -y
          yum install -y make
      - name: Build make
        working-directory: rpm/linux-build
        run: |
          make clean && make
